// Auto-generated by pb-typegen — DO NOT EDIT MANUALLY
// Regenerate: .miso/bin/pb-typegen

/** PocketBase 레코드 공통 필드 */
export interface BaseRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: string;
}

export interface UsersRecord extends BaseRecord {
  password: string;
  tokenKey: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name?: string;
  avatar?: string;
}

export interface MembersRecord extends BaseRecord {
  phone?: string;
  name?: string;
  addr1?: string;
  addr2?: string;
  addr3?: string;
  addr4?: string;
  zip?: string;
  phoneDup?: string;
  addrFlag?: string;
  phoneStatus?: string;
  userId?: string;
  birthDate?: string;
  email?: string;
  regDate?: string;
  phoneRaw?: string;
  addrRaw?: string;
  tel?: string;
  sourceIdx?: number;
}

