# -*- coding: utf-8 -*-
# [260904 upsert] POST /api/ops mode:'upsert' + keyCols (통합 시트·구분 한 칸): 키 같은 행 갱신, 없으면 추가 — 일일 입력 재시도 중복 행 원천 차단.
#   실행: python3 tools/phase7_upsert_260904.py (먼저 backups/ 로 cp)
import io
H='api/ym-db.pb.js'
h=io.open(H,encoding='utf-8').read()
def rep(a,b):
    global h
    assert h.count(a)==1, a[:70]
    h=h.replace(a,b)
rep('  var nri = meta.get("nextRowIndex") || 2;\n  var inserted = 0;\n  for (var i = 0; i < rows.length; i++) {\n    var data = {};\n    var src = alias ? alias.rowToPhys(rows[i] || {}) : (rows[i] || {});\n    var keys = Object.keys(src);\n    for (var ki = 0; ki < keys.length; ki++) data[keys[ki]] = src[keys[ki]];\n    var rec = new Record(col, { sheet: sheetKey, rowIndex: nri, data: data });\n    $app.save(rec);\n    nri++;\n    inserted++;\n  }','  var nri = meta.get("nextRowIndex") || 2;\n  var inserted = 0, updated = 0;\n  // [260904 upsert] mode:\'upsert\' + keyCols:[…] (통합 시트·구분 한 칸) — 키가 같은 행이 있으면 갱신, 없으면 추가. 재시도해도 중복 행이 안 생긴다.\n  var upKeys = (mode === "upsert" && alias && Array.isArray(body.keyCols) && body.keyCols.length) ? body.keyCols : null;\n  var upIdx = {};\n  if (upKeys) {\n    var cur = alias.findRows(col);\n    for (var ui = 0; ui < cur.length; ui++) { var ud = __alias.parseJson(cur[ui].publicExport().data, {}); if (!alias.isPart(ud)) continue; var uk = []; for (var uj = 0; uj < upKeys.length; uj++) uk.push(String(ud[upKeys[uj]] === undefined || ud[upKeys[uj]] === null ? "" : ud[upKeys[uj]]).trim()); var ukOk = true; for (var uq = 0; uq < uk.length; uq++) if (uk[uq] === "") ukOk = false; if (!ukOk) continue; upIdx[uk.join("\\u0001")] = cur[ui]; }\n  }\n  for (var i = 0; i < rows.length; i++) {\n    var data = {};\n    var src = alias ? alias.rowToPhys(rows[i] || {}) : (rows[i] || {});\n    var keys = Object.keys(src);\n    for (var ki = 0; ki < keys.length; ki++) data[keys[ki]] = src[keys[ki]];\n    if (upKeys) {\n      var kk = []; for (var kj = 0; kj < upKeys.length; kj++) kk.push(String(data[upKeys[kj]] === undefined || data[upKeys[kj]] === null ? "" : data[upKeys[kj]]).trim());\n      var kkey = kk.join("\\u0001"), kkOk = true; for (var kq = 0; kq < kk.length; kq++) if (kk[kq] === "") kkOk = false;\n      if (kkOk && upIdx[kkey]) {\n        var tgt = upIdx[kkey], td = __alias.parseJson(tgt.publicExport().data, {}), merged = {};\n        var tk = Object.keys(td || {}); for (var mi = 0; mi < tk.length; mi++) merged[tk[mi]] = td[tk[mi]];\n        var dk = Object.keys(data); for (var mj = 0; mj < dk.length; mj++) merged[dk[mj]] = data[dk[mj]];\n        tgt.set("data", merged); $app.save(tgt); updated++;\n        continue;\n      }\n    }\n    var rec = new Record(col, { sheet: sheetKey, rowIndex: nri, data: data });\n    $app.save(rec);\n    if (upKeys && kkOk) upIdx[kkey] = rec;\n    nri++;\n    inserted++;\n  }')
rep('  if (mode !== "append") {\n    // full replace: delete existing rows for this sheet (별칭이면 같은 구분의 행만)','  if (mode === "upsert" && !alias) return e.json(400, { error: "upsert requires part (unified sheet)" });   // [260904 upsert]\n  if (mode !== "append" && mode !== "upsert") {\n    // full replace: delete existing rows for this sheet (별칭이면 같은 구분의 행만)')
rep('  return e.json(200, { ok: true, inserted: inserted, removed: removed, via: sheetKey });','  return e.json(200, { ok: true, inserted: inserted, updated: updated, removed: removed, via: sheetKey });')
rep('  if (!alias && __alias.isUnifiedKey(sheetKey) && mode !== "append" && body.force !== true && localMetaGet(sheetKey)) {','  if (!alias && __alias.isUnifiedKey(sheetKey) && mode !== "append" && mode !== "upsert" && body.force !== true && localMetaGet(sheetKey)) {')
io.open(H,'w',encoding='utf-8').write(h)
print('OK phase7 upsert', len(h))
