# -*- coding: utf-8 -*-
# [260902] v46 파일 층 → DB 시트 전환(프로그램마스터·공연마스터_이력·일일입력_이력), ops 병합 폐기
import json
p='public/standalone.html'
s=open(p,encoding='utf-8').read()
P=json.loads("[[\"_pmLoading=fetch('data/db_v46/programs.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('db_v46 '+r.status);return r.json();}).then(function(list){\",\"_pmLoading=_pmSheetRows().then(function(list){   /* [260902] 프로그램 마스터 원천 = DB 시트 운영_프로그램마스터(v46 programs.json 이관본 · _json 컬럼에 원본 레코드, 사업ID→프로그램ID(YYMMDD_NN)+사업코드) */\"],[\"})(String(p.사업ID||'').charAt(12)) /* [WA80-v1] 기획/대관 = ID 13번째 글자 */,분야:\",\"})(String(p.구ID||p.사업ID||'').charAt(12)) /* [WA80-v1] 기획/대관 = 구ID(v46) 13번째 글자 · [260902] 사업ID는 프로그램ID로 바뀌어 구ID로 판정 */,사업코드:String(p.사업코드||''),분야:\"],[\"function _pmLoad(){\\n   if(_PM&&_BPL)return Promise.resolve({pm:_PM,bpl:_BPL});\",\"/* [260902] 운영_프로그램마스터 시트 → v46 programs.json과 같은 모양의 레코드 배열(_json 파싱). _pmLoad·_ymEduLoad 공용. */\\nvar _pmSheetP=null;\\nfunction _pmSheetRows(){\\n  if(_pmSheetP)return _pmSheetP;\\n  _pmSheetP=api('GET','/api/ops?sheet='+encodeURIComponent('프로그램마스터')).then(function(j){\\n    var list=[];\\n    ((j&&j.rows)||[]).forEach(function(r){ var o=null; try{ o=JSON.parse(r['_json']||''); }catch(_e){ o=null; } if(!o||typeof o!=='object')return; o.구ID=String(o.사업ID||r['구ID']||''); o.사업ID=String(r['프로그램ID']||o.사업ID||''); o.사업코드=String(r['사업코드']||''); list.push(o); });\\n    if(list.length<100)throw new Error('프로그램마스터 시트 비어있음');\\n    return list;\\n  }).catch(function(e){ _pmSheetP=null; throw e; });\\n  return _pmSheetP;\\n}\\nfunction _pmLoad(){\\n   if(_PM&&_BPL)return Promise.resolve({pm:_PM,bpl:_BPL});\"],[\"_ymEduP=fetch('data/db_v46/programs.json',{cache:'no-store'}).then(function(r){ if(!r.ok)throw new Error('HTTP '+r.status); return r.json(); }).then(function(j){ var rows=Array.isArray(j)?j:((j&&j.rows)||[]);\",\"_ymEduP=_pmSheetRows().then(function(j){ var rows=Array.isArray(j)?j:((j&&j.rows)||[]);   /* [260902] 원천 = 운영_프로그램마스터 시트 */\"],[\"fetch('data/db_v46/sales_merge_v46.json').then(function(r){ if(!r.ok)throw new Error('HTTP '+r.status); return r.json(); }).then(function(j){ _v46SalesMergeApply(j); })\",\"Promise.all([api('GET','/api/ops?sheet='+encodeURIComponent('공연마스터_이력')),api('GET','/api/ops?sheet='+encodeURIComponent('일일입력_이력'))]).then(function(a){ var master=((a[0]&&a[0].rows)||[]).map(function(m){ var o={}; Object.keys(m).forEach(function(k){ o[k]=m[k]; }); o._base=String(m['사업명']||''); o._yr=Number(String(m['시작일']||'').slice(0,4))||null; return o; }); var daily=((a[1]&&a[1].rows)||[]); return {master:master,daily:daily}; }).then(function(j){ _v46SalesMergeApply(j); })   /* [260902] 원천 = DB 시트 공연마스터_이력·일일입력_이력(v46 sales_merge 이관본, 프로그램ID 재키) */\"],[\"function _v46OpsMergeTick(){\\n  if(_v46om.done)return;\",\"function _v46OpsMergeTick(){\\n  _v46om.done=true; return;   /* [260902] 2026 대관 29행은 회차대장 시트로 이관 — 파일 병합 폐기 */\\n  if(_v46om.done)return;\"]]")
ok=0
for a,b in P:
    n=s.count(a)
    assert n==1, 'anchor count=%d: %s'%(n,a[:50])
    s=s.replace(a,b); ok+=1
open(p,'w',encoding='utf-8').write(s)
print('replaced ok %d/%d'%(ok,len(P)))
